// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include "main.hpp"

// ─────────────────────────────────────────────────────────────────────────────
// [T1]  small shift count on small arrays
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T1a: shiftleft([1,2,3,4,5], 5, 3) -> [4,5,1,2,3]", "[T1]")
{
    int n[] = {1, 2, 3, 4, 5};
    shiftleft(n, 5, 3);
    int exp[] = {4, 5, 1, 2, 3};
    for (int i = 0; i < 5; i++) REQUIRE(n[i] == exp[i]);
}

TEST_CASE("T1b: shiftleft([10,13,5,7,2], 5, 1) -> [13,5,7,2,10]", "[T1]")
{
    int n[] = {10, 13, 5, 7, 2};
    shiftleft(n, 5, 1);
    int exp[] = {13, 5, 7, 2, 10};
    for (int i = 0; i < 5; i++) REQUIRE(n[i] == exp[i]);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T2]  shift count == SIZE/2
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T2a: shiftleft 10-element array by 5 swaps two halves", "[T2]")
{
    int n[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
    shiftleft(n, 10, 5);
    int exp[] = {5, 6, 7, 8, 9, 0, 1, 2, 3, 4};
    for (int i = 0; i < 10; i++) REQUIRE(n[i] == exp[i]);
}

TEST_CASE("T2b: shiftleft 6-element array by 3 swaps two halves", "[T2]")
{
    int n[] = {1, 2, 3, 4, 5, 6};
    shiftleft(n, 6, 3);
    int exp[] = {4, 5, 6, 1, 2, 3};
    for (int i = 0; i < 6; i++) REQUIRE(n[i] == exp[i]);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T3]  shift count > SIZE — modular handling
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T3a: shiftleft([11,22,33,44,55], 5, 6) == shift by 1 -> [22,33,44,55,11]", "[T3]")
{
    int n[] = {11, 22, 33, 44, 55};
    shiftleft(n, 5, 6);
    int exp[] = {22, 33, 44, 55, 11};
    for (int i = 0; i < 5; i++) REQUIRE(n[i] == exp[i]);
}

TEST_CASE("T3b: shiftleft 4-element array by 11 == shift by 3", "[T3]")
{
    int n[] = {1, 2, 3, 4};
    shiftleft(n, 4, 11);
    // 11 % 4 == 3
    int exp[] = {4, 1, 2, 3};
    for (int i = 0; i < 4; i++) REQUIRE(n[i] == exp[i]);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T4]  edge cases — count = 0 and count = SIZE (both no-op)
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T4a: shiftleft by 0 leaves array unchanged", "[T4]")
{
    int n[] = {7, 7, 8, 8, 9};
    int org[] = {7, 7, 8, 8, 9};
    shiftleft(n, 5, 0);
    for (int i = 0; i < 5; i++) REQUIRE(n[i] == org[i]);
}

TEST_CASE("T4b: shiftleft by SIZE leaves array unchanged", "[T4]")
{
    int n[] = {3, 1, 4, 1, 5, 9, 2, 6};
    int org[] = {3, 1, 4, 1, 5, 9, 2, 6};
    shiftleft(n, 8, 8);
    for (int i = 0; i < 8; i++) REQUIRE(n[i] == org[i]);
}
